# Generated by Django 4.1.3 on 2022-11-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='Sphone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='Semail',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='Sname',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(choices=[['male', 'Male'], ['female', 'Female']], default='2020-01-10', max_length=25),
            preserve_default=False,
        ),
    ]
